import { valueSets } from './valueSets';
import { localizationMap } from './localization';

export type OptionType = 'float' | 'int' | 'bool';

export interface SandboxOptionDependency {
    sourceOptionId: number;
    triggerValueIndices: number[];
    targetOptionIds: number[];
}

export interface SandboxOption {
    id: number;
    enumName: string;
    category: string;
    type: OptionType;
    defaultCode: string;
    defaultValueIndex: number;
    valueSetName: string;
    uiSection: boolean;
    dependencies: SandboxOptionDependency[];
}

export const getDisplayName = (enumName: string) => localizationMap[`go${enumName}`] || enumName;
export const getDescription = (enumName: string) => localizationMap[`go${enumName}Desc`] || "";

export const sandboxOptions: SandboxOption[] = [
    { id: 0, enumName: "RangedDamage", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 1, enumName: "MeleeDamage", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 2, enumName: "BlockDamage", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 3, enumName: "TerrainDamage", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 4, enumName: "HeadshotMultiplier", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 17, enumName: "IncomingDamage", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 6, enumName: "WalkSpeed", category: "General", type: "float", defaultCode: "G", defaultValueIndex: 6, valueSetName: "PlayerSpeedValuesWithNone", uiSection: true, dependencies: [] },
    { id: 7, enumName: "RunSpeed", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "PlayerSpeedValues", uiSection: false, dependencies: [] },
    { id: 5, enumName: "CrouchSpeed", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "PlayerSpeedValues", uiSection: false, dependencies: [] },
    { id: 112, enumName: "CrouchRunSpeed", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "PlayerSpeedValues", uiSection: false, dependencies: [] },
    { id: 8, enumName: "JumpStrength", category: "General", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "JumpStrength", uiSection: false, dependencies: [] },
    { id: 10, enumName: "StaminaRegen", category: "General", type: "float", defaultCode: "D", defaultValueIndex: 3, valueSetName: "StaminaRegen", uiSection: false, dependencies: [] },
    { id: 9, enumName: "StaminaUsage", category: "General", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "StaminaUsage", uiSection: false, dependencies: [{ sourceOptionId: 9, triggerValueIndices: [0], targetOptionIds: [10] }] },
    { id: 18, enumName: "XPMultiplier", category: "General", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "XPGain", uiSection: true, dependencies: [{ sourceOptionId: 18, triggerValueIndices: [0], targetOptionIds: [19] }] },
    { id: 19, enumName: "ShowXP", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "ShowXP", uiSection: false, dependencies: [] },
    { id: 11, enumName: "PlayerLevelBonusApplied", category: "General", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 116, enumName: "SkillGainRate", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "SkillGainRate", uiSection: false, dependencies: [] },
    { id: 117, enumName: "SkillPointsPerLevel", category: "General", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "PointsPer", uiSection: false, dependencies: [] },
    { id: 26, enumName: "DeathPenalty", category: "General", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "DeathPenalty", uiSection: true, dependencies: [] },
    { id: 22, enumName: "LoseItemsOnDeathType", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "LoseItemsOnDeathType", uiSection: false, dependencies: [{ sourceOptionId: 22, triggerValueIndices: [0], targetOptionIds: [23] }] },
    { id: 23, enumName: "LoseItemsOnDeathCount", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "LoseItemCount", uiSection: false, dependencies: [] },
    { id: 24, enumName: "DegradeItemsOnDeath", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "DegradeItemsOnDeath", uiSection: false, dependencies: [{ sourceOptionId: 24, triggerValueIndices: [0], targetOptionIds: [25] }] },
    { id: 25, enumName: "DegradeAmountOnDeath", category: "General", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "MaxDegradationAmounts", uiSection: false, dependencies: [] },
    { id: 27, enumName: "DropOnDeath", category: "General", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "DropOnDeath", uiSection: false, dependencies: [] },
    { id: 28, enumName: "DropOnQuit", category: "General", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "DropOnQuit", uiSection: false, dependencies: [] },
    { id: 29, enumName: "InfectionRate", category: "General", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 15, enumName: "NewbieCoat", category: "General", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 20, enumName: "EncumbranceModifier", category: "General", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "Encumbrance", uiSection: false, dependencies: [] },
    { id: 12, enumName: "JarRefund", category: "General", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "JarRefund", uiSection: false, dependencies: [] },
    { id: 30, enumName: "EnemySpawnMode", category: "Entities", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: true, dependencies: [{ sourceOptionId: 30, triggerValueIndices: [0], targetOptionIds: [43, 46, 44, 45, 31, 42, 32, 33, 16, 13, 14, 34, 35, 36, 37, 38, 39, 41] }] },
    { id: 43, enumName: "MaxEnemyTier", category: "Entities", type: "int", defaultCode: "F", defaultValueIndex: 5, valueSetName: "MaxEnemyType", uiSection: false, dependencies: [] },
    { id: 46, enumName: "BiomeEnemyDensity", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "BiomeEnemyDensity", uiSection: false, dependencies: [] },
    { id: 44, enumName: "BiomeZombieRespawn", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "SlowToFast", uiSection: false, dependencies: [] },
    { id: 45, enumName: "BiomeAnimalRespawn", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "SlowToFast", uiSection: false, dependencies: [] },
    { id: 31, enumName: "EntityDamage", category: "Entities", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: true, dependencies: [] },
    { id: 42, enumName: "EntityIncomingDamage", category: "Entities", type: "float", defaultCode: "G", defaultValueIndex: 6, valueSetName: "DamageValuesNoNone", uiSection: false, dependencies: [] },
    { id: 32, enumName: "BlockDamageAI", category: "Entities", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 33, enumName: "BlockDamageAIBM", category: "Entities", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 16, enumName: "HeadshotMode", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "HeadshotMode", uiSection: false, dependencies: [] },
    { id: 13, enumName: "ShowHealthBars", category: "Entities", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 14, enumName: "ShowEnemyDamage", category: "Entities", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 34, enumName: "ZombieMove", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "ZombieSpeeds", uiSection: true, dependencies: [] },
    { id: 35, enumName: "ZombieMoveNight", category: "Entities", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "ZombieSpeeds", uiSection: false, dependencies: [] },
    { id: 36, enumName: "ZombieFeralMove", category: "Entities", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "ZombieSpeeds", uiSection: false, dependencies: [] },
    { id: 37, enumName: "ZombieBMMove", category: "Entities", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "ZombieSpeeds", uiSection: false, dependencies: [] },
    { id: 38, enumName: "ZombieFeralSense", category: "Entities", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "ZombieFeralSense", uiSection: true, dependencies: [] },
    { id: 39, enumName: "AISmellMode", category: "Entities", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "AISmellMode", uiSection: false, dependencies: [] },
    { id: 41, enumName: "ZombieRageChance", category: "Entities", type: "float", defaultCode: "B", defaultValueIndex: 1, valueSetName: "ZombieRageChance", uiSection: false, dependencies: [] },
    { id: 40, enumName: "AllowZombieDigging", category: "Entities", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 47, enumName: "ZombiesEatAnimals", category: "Entities", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 60, enumName: "GlobalGSModifier", category: "World", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 61, enumName: "BiomeGSModifier", category: "World", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 55, enumName: "BiomeProgression", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 56, enumName: "TemperatureSurvival", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 74, enumName: "MaxTechType", category: "World", type: "int", defaultCode: "E", defaultValueIndex: 4, valueSetName: "MaxTechType", uiSection: false, dependencies: [] },
    { id: 73, enumName: "WorkstationsInTheWild", category: "World", type: "float", defaultCode: "A", defaultValueIndex: 0, valueSetName: "JarRefund", uiSection: false, dependencies: [] },
    { id: 48, enumName: "BloodMoonFrequency", category: "World", type: "int", defaultCode: "H", defaultValueIndex: 7, valueSetName: "BloodMoonFrequency", uiSection: true, dependencies: [{ sourceOptionId: 48, triggerValueIndices: [0], targetOptionIds: [49, 51, 50] }] },
    { id: 49, enumName: "BloodMoonRange", category: "World", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "BloodMoonRange", uiSection: false, dependencies: [] },
    { id: 51, enumName: "BloodMoonEnemyCount", category: "World", type: "int", defaultCode: "C", defaultValueIndex: 2, valueSetName: "BloodMoonCount", uiSection: false, dependencies: [] },
    { id: 50, enumName: "BloodMoonWarning", category: "World", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "BloodMoonWarning", uiSection: false, dependencies: [] },
    { id: 52, enumName: "AirDropFrequency", category: "World", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "AirDrops", uiSection: false, dependencies: [{ sourceOptionId: 52, triggerValueIndices: [0], targetOptionIds: [54, 53] }] },
    { id: 54, enumName: "AirDropRandomTime", category: "World", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "AirDropRandomTime", uiSection: false, dependencies: [] },
    { id: 57, enumName: "StormFreq", category: "World", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "StormFrequency", uiSection: true, dependencies: [{ sourceOptionId: 57, triggerValueIndices: [0], targetOptionIds: [58] }] },
    { id: 58, enumName: "StormWarning", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 59, enumName: "HeatMapSensitivity", category: "World", type: "float", defaultCode: "D", defaultValueIndex: 3, valueSetName: "DisabledLowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 66, enumName: "DayNightLength", category: "World", type: "int", defaultCode: "F", defaultValueIndex: 5, valueSetName: "DayNightLength", uiSection: true, dependencies: [] },
    { id: 67, enumName: "DayLightLength", category: "World", type: "int", defaultCode: "I", defaultValueIndex: 8, valueSetName: "DayLightLength", uiSection: true, dependencies: [] },
    { id: 53, enumName: "AirDropMarker", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: true, dependencies: [] },
    { id: 68, enumName: "AllowMap", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 69, enumName: "AllowCompass", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 70, enumName: "AllowScreenMarkers", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 71, enumName: "ShowLocationInfo", category: "World", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "ShowLocationTypes", uiSection: false, dependencies: [] },
    { id: 72, enumName: "ShowDayTime", category: "World", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [{ sourceOptionId: 72, triggerValueIndices: [0], targetOptionIds: [50] }] },
    { id: 77, enumName: "LootMaxTier", category: "Resources", type: "int", defaultCode: "F", defaultValueIndex: 5, valueSetName: "ItemTierOptions", uiSection: false, dependencies: [] },
    { id: 62, enumName: "GlobalLSModifier", category: "Resources", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 63, enumName: "BiomeLSModifier", category: "Resources", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 64, enumName: "POITierLSModifier", category: "Resources", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 75, enumName: "LootRespawnDays", category: "Resources", type: "int", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LootRespawnDays", uiSection: true, dependencies: [] },
    { id: 76, enumName: "LootTimer", category: "Resources", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: false, dependencies: [] },
    { id: 90, enumName: "LootBagChance", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 78, enumName: "GlobalLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: true, dependencies: [{ sourceOptionId: 78, triggerValueIndices: [0], targetOptionIds: [79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 111] }] },
    { id: 79, enumName: "FoodLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 80, enumName: "DrinkLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 81, enumName: "MedicalLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 82, enumName: "AmmoLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 83, enumName: "ResourceLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 84, enumName: "ArmorLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 85, enumName: "MeleeLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 86, enumName: "RangedLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 87, enumName: "DukesLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 88, enumName: "CraftingMagazinesLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 111, enumName: "BookLootCount", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 89, enumName: "TreasureMapChance", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "PlayerSpeedValues", uiSection: false, dependencies: [] },
    { id: 101, enumName: "MiningOutput", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: true, dependencies: [] },
    { id: 91, enumName: "CropOutput", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 92, enumName: "SeedDropOutput", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: false, dependencies: [] },
    { id: 102, enumName: "HarvestingOutput", category: "Resources", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "LootAbundanceValues", uiSection: true, dependencies: [] },
    { id: 93, enumName: "CropGrowthSpeed", category: "Resources", type: "float", defaultCode: "F", defaultValueIndex: 5, valueSetName: "CropGrowthSpeed", uiSection: true, dependencies: [] },
    { id: 96, enumName: "CraftingProgression", category: "Crafting", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: true, dependencies: [] },
    { id: 100, enumName: "CraftingMaxTier", category: "Crafting", type: "int", defaultCode: "F", defaultValueIndex: 5, valueSetName: "ItemTierOptions", uiSection: false, dependencies: [] },
    { id: 115, enumName: "PointsPerMagazine", category: "Crafting", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "PointsPer", uiSection: true, dependencies: [] },
    { id: 94, enumName: "BackpackCrafting", category: "Crafting", type: "int", defaultCode: "B", defaultValueIndex: 1, valueSetName: "BackpackCrafting", uiSection: true, dependencies: [] },
    { id: 95, enumName: "WorkstationCrafting", category: "Crafting", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 104, enumName: "SmeltingType", category: "Crafting", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "SmeltingType", uiSection: true, dependencies: [] },
    { id: 97, enumName: "CraftingTime", category: "Crafting", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 98, enumName: "CraftingInput", category: "Crafting", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 99, enumName: "CraftingOutput", category: "Crafting", type: "float", defaultCode: "D", defaultValueIndex: 3, valueSetName: "StaminaRegen", uiSection: false, dependencies: [] },
    { id: 103, enumName: "ScrappingOutput", category: "Crafting", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 105, enumName: "DewCollectorTime", category: "Crafting", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 106, enumName: "DewCollectorOutput", category: "Crafting", type: "float", defaultCode: "A", defaultValueIndex: 0, valueSetName: "CollectorOutput", uiSection: false, dependencies: [] },
    { id: 107, enumName: "DewCollectorInput", category: "Crafting", type: "float", defaultCode: "B", defaultValueIndex: 1, valueSetName: "DewCollectorInput", uiSection: true, dependencies: [] },
    { id: 108, enumName: "ApiaryTime", category: "Crafting", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "SpeedValues", uiSection: true, dependencies: [] },
    { id: 109, enumName: "ApiaryOutput", category: "Crafting", type: "float", defaultCode: "A", defaultValueIndex: 0, valueSetName: "CollectorOutput", uiSection: false, dependencies: [] },
    { id: 110, enumName: "ApiaryInput", category: "Crafting", type: "float", defaultCode: "F", defaultValueIndex: 5, valueSetName: "ApiaryInput", uiSection: true, dependencies: [] },
    { id: 21, enumName: "ItemDegradation", category: "Crafting", type: "float", defaultCode: "D", defaultValueIndex: 3, valueSetName: "DisabledLowDefaultHigh", uiSection: true, dependencies: [] },
    { id: 113, enumName: "RepairTypes", category: "Crafting", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "RepairTypes", uiSection: true, dependencies: [] },
    { id: 114, enumName: "MaxDegradationAmount", category: "Crafting", type: "float", defaultCode: "A", defaultValueIndex: 0, valueSetName: "MaxDegradationAmounts", uiSection: true, dependencies: [] },
    { id: 128, enumName: "TradersEnabled", category: "Traders", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [{ sourceOptionId: 128, triggerValueIndices: [0], targetOptionIds: [136, 134, 133, 130, 131, 135, 65] }] },
    { id: 129, enumName: "VendingEnabled", category: "Traders", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [{ sourceOptionId: 129, triggerValueIndices: [0], targetOptionIds: [138, 137] }] },
    { id: 127, enumName: "TraderHours", category: "Traders", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "TraderHourPresets", uiSection: false, dependencies: [] },
    { id: 132, enumName: "TraderProtection", category: "Traders", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "TraderArea", uiSection: false, dependencies: [] },
    { id: 126, enumName: "TraderDialog", category: "Traders", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 65, enumName: "GlobalTSModifier", category: "Traders", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: true, dependencies: [] },
    { id: 136, enumName: "TraderMaxTier", category: "Traders", type: "int", defaultCode: "F", defaultValueIndex: 5, valueSetName: "ItemTierOptions", uiSection: false, dependencies: [] },
    { id: 134, enumName: "TraderItemAbundance", category: "Traders", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 138, enumName: "VendingItemAbundance", category: "Traders", type: "float", defaultCode: "C", defaultValueIndex: 2, valueSetName: "LowDefaultHigh", uiSection: false, dependencies: [] },
    { id: 133, enumName: "TraderResetInterval", category: "Traders", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "TraderResetInterval", uiSection: false, dependencies: [] },
    { id: 137, enumName: "VendingResetInterval", category: "Traders", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "TraderResetInterval", uiSection: false, dependencies: [] },
    { id: 130, enumName: "TraderSellPrices", category: "Traders", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "BarterValues", uiSection: false, dependencies: [] },
    { id: 131, enumName: "TraderBuyPrices", category: "Traders", type: "float", defaultCode: "E", defaultValueIndex: 4, valueSetName: "BarterValues", uiSection: false, dependencies: [] },
    { id: 135, enumName: "TraderBuyLimit", category: "Traders", type: "int", defaultCode: "D", defaultValueIndex: 3, valueSetName: "StarterSkillPoints", uiSection: false, dependencies: [] },
    { id: 139, enumName: "ChallengesEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [{ sourceOptionId: 139, triggerValueIndices: [0], targetOptionIds: [140] }] },
    { id: 118, enumName: "QuestsEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 140, enumName: "IntroChallengesEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 119, enumName: "IntroQuestEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 120, enumName: "TraderToTraderQuestsEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 124, enumName: "BuriedQuestsEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 125, enumName: "POIQuestsEnabled", category: "Tasks", type: "bool", defaultCode: "B", defaultValueIndex: 1, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 122, enumName: "QuestsPerTier", category: "Tasks", type: "int", defaultCode: "K", defaultValueIndex: 10, valueSetName: "QuestPerTier", uiSection: false, dependencies: [] },
    { id: 123, enumName: "QuestProgressionDailyLimit", category: "Tasks", type: "int", defaultCode: "E", defaultValueIndex: 4, valueSetName: "QuestPerDay", uiSection: false, dependencies: [] },
    { id: 121, enumName: "StarterSkillPoints", category: "Tasks", type: "int", defaultCode: "E", defaultValueIndex: 4, valueSetName: "StarterSkillPoints", uiSection: false, dependencies: [] },
    { id: 141, enumName: "VehicleFuelUsage", category: "Misc", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 142, enumName: "VehicleEntityDamage", category: "Misc", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 143, enumName: "VehicleBlockDamage", category: "Misc", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 144, enumName: "VehicleSelfDamage", category: "Misc", type: "float", defaultCode: "H", defaultValueIndex: 7, valueSetName: "DamageValues", uiSection: false, dependencies: [] },
    { id: 145, enumName: "ElectricalOutput", category: "Misc", type: "float", defaultCode: "D", defaultValueIndex: 3, valueSetName: "StaminaRegen", uiSection: true, dependencies: [] },
    { id: 146, enumName: "SillyCelebrate", category: "Misc", type: "int", defaultCode: "A", defaultValueIndex: 0, valueSetName: "Celebrate", uiSection: true, dependencies: [] },
    { id: 147, enumName: "SillyBigHeads", category: "Misc", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 148, enumName: "SillyTinyZombies", category: "Misc", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 150, enumName: "SillyLowGravity", category: "Misc", type: "float", defaultCode: "F", defaultValueIndex: 5, valueSetName: "Gravity", uiSection: false, dependencies: [] },
    { id: 149, enumName: "SillySounds", category: "Misc", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] },
    { id: 151, enumName: "SillyBlackandWhite", category: "Misc", type: "bool", defaultCode: "A", defaultValueIndex: 0, valueSetName: "YesNo", uiSection: false, dependencies: [] }
];

export const optionsById: Map<number, SandboxOption> = new Map(
    sandboxOptions.map(o => [o.id, o])
);