export const localizationMap: Record<string, string> = {
    "goRangedDamage": "Ranged Damage",
    "goMeleeDamage": "Melee Damage",
    "goBlockDamage": "Block Damage",
    "goTerrainDamage": "Terrain Damage",
    "goHeadshotMultiplier": "Headshot Multiplier",
    "goIncomingDamage": "Incoming Damage",
    "goWalkSpeed": "Walk Speed",
    "goRunSpeed": "Run Speed",
    "goCrouchSpeed": "Crouch Speed",
    "goCrouchRunSpeed": "Crouch Run Speed",
    "goJumpStrength": "Jump Height",
    "goStaminaRegen": "Stamina Regen",
    "goStaminaUsage": "Stamina Usage",
    "goXPMultiplier": "XP Multiplier",
    "goShowXP": "Show XP",
    "goPlayerLevelBonusApplied": "Level Health/Stam Bonus",
    "goSkillGainRate": "Skill Gain Rate",
    "goSkillPointsPerLevel": "Skill Gain Amount",
    "goDeathPenalty": "Death Penalty",
    "goLoseItemsOnDeathType": "Lose Items Death Type",
    "goLoseItemsOnDeathCount": "Lose Items Death Count",
    "goDegradeItemsOnDeath": "Degrade Items On Death",
    "goDegradeAmountOnDeath": "Degrade Amount On Death",
    "goDropOnDeath": "Drop On Death",
    "goDropOnQuit": "Drop On Quit",
    "goInfectionRate": "Infection Rate",
    "goNewbieCoat": "Allow Newbie Coat",
    "goEncumbranceModifier": "Encumbrance Modifier",
    "goJarRefund": "Jar Refund",
    "goEnemySpawnMode": "Enemy Spawn",
    "goMaxEnemyTier": "Max Enemy Type",
    "goBiomeEnemyDensity": "Biome Enemy Density",
    "goBiomeZombieRespawn": "Biome Enemy Respawn",
    "goBiomeAnimalRespawn": "Biome Animal Respawn",
    "goEntityDamage": "Entity Damage",
    "goEntityIncomingDamage": "Entity Incoming Damage",
    "goBlockDamageAI": "Entity Block Damage",
    "goBlockDamageAIBM": "Blood Moon Block Damage",
    "goHeadshotMode": "Headshot Mode",
    "goShowHealthBars": "Entity Health Bars",
    "goShowEnemyDamage": "Show Entity Damage",
    "goZombieMove": "Zombie Day Speed",
    "goZombieMoveNight": "Zombie Night Speed",
    "goZombieFeralMove": "Zombie Feral Speed",
    "goZombieBMMove": "Zombie Blood Moon Speed",
    "goZombieFeralSense": "Zombie Feral Sense",
    "goAISmellMode": "Zombie AI Smell Mode",
    "goZombieRageChance": "Zombie Rage Chance",
    "goAllowZombieDigging": "Allow Zombie Digging",
    "goZombiesEatAnimals": "Zombies Eat Animals",
    "goGlobalGSModifier": "Global GameStage",
    "goBiomeGSModifier": "Biome GameStage",
    "goBiomeProgression": "Biome Progression",
    "goTemperatureSurvival": "Temperature Survival",
    "goMaxTechType": "Max Tech Type",
    "goWorkstationsInTheWild": "Workstations in the Wild",
    "goBloodMoonFrequency": "Blood Moon Frequency",
    "goBloodMoonRange": "Blood Moon Range",
    "goBloodMoonEnemyCount": "Blood Moon Count",
    "goBloodMoonWarning": "Blood Moon Warning",
    "goAirDropFrequency": "Air Drops",
    "goAirDropRandomTime": "Air Drop Random Time",
    "goStormFreq": "Storm Frequency",
    "goStormWarning": "Storm Warning",
    "goHeatMapSensitivity": "Heatmap Sensitivity",
    "goDayNightLength": "24 Day Cycle",
    "goDayLightLength": "Day Light Length",
    "goAirDropMarker": "Mark Air Drops",
    "goAllowMap": "Allow Map",
    "goAllowCompass": "Allow Compass",
    "goAllowScreenMarkers": "Allow Screen Markers",
    "goShowLocationInfo": "Show Location Info",
    "goShowDayTime": "Show Day/Time",
    "goLootMaxTier": "Loot Max Tier",
    "goGlobalLSModifier": "Global LootStage",
    "goBiomeLSModifier": "Biome LootStage",
    "goPOITierLSModifier": "POI Tier LootStage",
    "goLootRespawnDays": "Loot Respawn Days",
    "goLootTimer": "Loot Time",
    "goLootBagChance": "Loot Bag Chance",
    "goGlobalLootCount": "Global Loot Abundance",
    "goFoodLootCount": "Food Abundance",
    "goDrinkLootCount": "Drink Abundance",
    "goMedicalLootCount": "Medical Abundance",
    "goAmmoLootCount": "Ammo Abundance",
    "goResourceLootCount": "Resource Abundance",
    "goArmorLootCount": "Armor Abundance",
    "goMeleeLootCount": "Melee Abundance",
    "goRangedLootCount": "Ranged Abundance",
    "goDukesLootCount": "Dukes Abundance",
    "goCraftingMagazinesLootCount": "Magazines Abundance",
    "goBookLootCount": "Book Abundance",
    "goTreasureMapChance": "Treasure Map Chance",
    "goMiningOutput": "Mining Output",
    "goCropOutput": "Crop Output",
    "goSeedDropOutput": "Seed Drop Output",
    "goHarvestingOutput": "Harvesting Output",
    "goCropGrowthSpeed": "Crop Growth",
    "goCraftingProgression": "Crafting Progression",
    "goCraftingMaxTier": "Crafting Max Tier",
    "goPointsPerMagazine": "Magazine Points",
    "goBackpackCrafting": "Backpack Crafting",
    "goWorkstationCrafting": "Workstation Crafting",
    "goSmeltingType": "Smelter Type",
    "goCraftingTime": "Crafting Time",
    "goCraftingInput": "Crafting Input",
    "goCraftingOutput": "Crafting Output",
    "goScrappingOutput": "Scrapping Output",
    "goDewCollectorTime": "Dew Collector Time",
    "goDewCollectorOutput": "Dew Collector Output",
    "goDewCollectorInput": "Dew Collector Input",
    "goApiaryTime": "Apiary Time",
    "goApiaryOutput": "Apiary Output",
    "goApiaryInput": "Apiary Input",
    "goItemDegradation": "Item Degradation",
    "goRepairTypes": "Item Repair Types",
    "goMaxDegradationAmount": "Max Degrade Amount",
    "goTradersEnabled": "Trading Enabled",
    "goVendingEnabled": "Vending Machines Enabled",
    "goTraderHours": "Trader Hours",
    "goTraderProtection": "Trader Protection",
    "goTraderDialog": "Trading Dialog",
    "goGlobalTSModifier": "Global TraderStage",
    "goTraderMaxTier": "Trader Max Tier",
    "goTraderItemAbundance": "Trader Item Abundance",
    "goVendingItemAbundance": "Vending Item Abundance",
    "goTraderResetInterval": "Trader Reset Interval",
    "goVendingResetInterval": "Vending Reset Interval",
    "goTraderSellPrices": "Traders Sell Price",
    "goTraderBuyPrices": "Traders Buy Price",
    "goTraderBuyLimit": "Trader Buy Limit",
    "goChallengesEnabled": "Challenges Enabled",
    "goQuestsEnabled": "Quests Enabled",
    "goIntroChallengesEnabled": "Intro Challenges Enabled",
    "goIntroQuestEnabled": "Intro Quest Enabled",
    "goTraderToTraderQuestsEnabled": "Trader to Trader Quests",
    "goBuriedQuestsEnabled": "Buried Quests Enabled",
    "goPOIQuestsEnabled": "POI Quests Enabled",
    "goQuestsPerTier": "Quests per Tier",
    "goQuestProgressionDailyLimit": "Quests per Day",
    "goStarterSkillPoints": "Starter Skill Points",
    "goVehicleFuelUsage": "Vehicle Fuel Usage",
    "goVehicleEntityDamage": "Vehicle Entity Damage",
    "goVehicleBlockDamage": "Vehicle Block Damage",
    "goVehicleSelfDamage": "Vehicle Self Damage",
    "goElectricalOutput": "Electrical Output",
    "goSillyCelebrate": "Celebrate Kills",
    "goSillyBigHeads": "Big Heads",
    "goSillyTinyZombies": "Tiny Zombies",
    "goSillyLowGravity": "Gravity",
    "goSillySounds": "Silly Sounds",
    "goSillyBlackandWhite": "Black and White",

    // Descriptions
    "goRangedDamageDesc": "Damage dealt by the player with bows",
    "goMeleeDamageDesc": "Damage dealt by the player with melee weapons and tools.",
    "goBlockDamageDesc": "How much damage players deal to blocks with tools and weapons.",
    "goTerrainDamageDesc": "How much damage players deal to terrain.",
    "goHeadshotMultiplierDesc": "Multiplier applied to headshot damage players deal to entities.",
    "goIncomingDamageDesc": "How much damage the player receives from all sources.",
    "goWalkSpeedDesc": "Adjusts player movement speed while walking.",
    "goRunSpeedDesc": "Adjusts player movement speed while running.",
    "goCrouchSpeedDesc": "Adjusts player movement speed while crouching and walking.",
    "goCrouchRunSpeedDesc": "Adjusts player movement speed while crouching and running.",
    "goJumpStrengthDesc": "Modifies player jump height.",
    "goStaminaRegenDesc": "Controls the rate stamina regenerates. Values are approximate.",
    "goStaminaUsageDesc": "Stamina cost for actions like running",
    "goXPMultiplierDesc": "Multiplier applied to all experience gained.",
    "goShowXPDesc": "Hide or show the XP bar and XP pop-up on screen.",
    "goPlayerLevelBonusAppliedDesc": "Determines whether health and stamina increase per level.",
    "goSkillGainRateDesc": "Adjusts how many levels are required to earn skill points.",
    "goSkillPointsPerLevelDesc": "Controls how many skill points are gained when skill points are awarded.",
    "goDeathPenaltyDesc": "Determines the death penalty applied after death.",
    "goLoseItemsOnDeathTypeDesc": "Sets which items are considered for loss on death.",
    "goLoseItemsOnDeathCountDesc": "Sets the number of random items lost on death.",
    "goDegradeItemsOnDeathDesc": "Sets whether items degrade on death. None = no loss. Durability = Reduces an amount of current durability",
    "goDegradeAmountOnDeathDesc": "When Death Degradation is enabled",
    "goDropOnDeathDesc": "Which items are dropped on death.",
    "goDropOnQuitDesc": "Which items are dropped on quit. Nothing = Drop nothing. Everything = Drop both backpack and toolbelt. Toolbelt = Drop items on toolbelt. Backpack = Drop items in the backpack.",
    "goInfectionRateDesc": "Adjusts how quickly infections progress.",
    "goNewbieCoatDesc": "If enabled",
    "goEncumbranceModifierDesc": "Controls the number of encumbered backpack slots. Values are Disabled (no encumbrance) to Full (maximum encumbrance). Default uses XML config values.",
    "goJarRefundDesc": "Chance of jars returned from consuming items.",
    "goEnemySpawnModeDesc": "Enable or disable enemy spawning.",
    "goMaxEnemyTierDesc": "Highest tier of zombie types that can spawn.",
    "goBiomeEnemyDensityDesc": "Overrides biome enemy density and sets how many enemies spawn in each biome. Default uses XML config values.",
    "goBiomeZombieRespawnDesc": "Increases the respawn rate of enemies in active biomes. Default uses XML config values.",
    "goBiomeAnimalRespawnDesc": "Increases the respawn rate of animals in active biomes. Affects non-zombie passive and aggressive food sources. Default uses XML config values.",
    "goEntityDamageDesc": "Controls how much damage enemies do to players. This stacks with other incoming damage players receive.",
    "goEntityIncomingDamageDesc": "Damage entities",
    "goBlockDamageAIDesc": "How much damage enemies deal to blocks.",
    "goBlockDamageAIBMDesc": "Damage enemies do to blocks during Blood Moons.",
    "goHeadshotModeDesc": "Determines how headshot damage is handled. Headshot Only = enemies can only be damaged by headshots. Headshot Finisher = body shots deal damage",
    "goShowHealthBarsDesc": "Show or hide entity health bars.",
    "goShowEnemyDamageDesc": "Display floating damage numbers when entities are hit.",
    "goZombieMoveDesc": "Sets zombie movement speed during daytime for normal zombies. Does not affect ferals and specials.",
    "goZombieMoveNightDesc": "Sets zombie movement speed at night for normal zombies. Does not affect ferals and specials.",
    "goZombieFeralMoveDesc": "Sets movement speed of feral zombies.",
    "goZombieBMMoveDesc": "Controls zombie movement speed during Blood Moon hordes and storms.",
    "goZombieFeralSenseDesc": "How easily zombies detect players through sight and sound.",
    "goAISmellModeDesc": "Enable or disable zombie scent tracking",
    "goZombieRageChanceDesc": "Chance for zombies to enter rage mode when damaged.",
    "goAllowZombieDiggingDesc": "Allow zombies to dig down through terrain. Can still dig sideways.",
    "goZombiesEatAnimalsDesc": "Determines whether zombies eat animal corpses.",
    "goGlobalGSModifierDesc": "Determines enemy types",
    "goBiomeGSModifierDesc": "Biome based difficulty modifier. Harder biomes raise enemy strength and loot stage beyond your base progression. Default uses XML config values.",
    "goBiomeProgressionDesc": "Enable biome hazards. Weather and Storms are not affected by this setting.",
    "goTemperatureSurvivalDesc": "Controls whether environmental temperature (hot and cold) affect the player.",
    "goMaxTechTypeDesc": "Globally sets the highest available tech type for weapons and items allowing control over progression and gameplay pacing.",
    "goWorkstationsInTheWildDesc": "Allow functional workstations to spawn in world. Applied on new Navezgane or RWG map generation.",
    "goBloodMoonFrequencyDesc": "Number of in-game days between Blood Moons. Disabled = No Blood Moons.",
    "goBloodMoonRangeDesc": "Number of days after Blood Moon frequency the event can occur. For example: A frequency of 7 + a range of 5 randomizes the Blood Moon between day 7 and day 12. 0 Days = No randomness.",
    "goBloodMoonEnemyCountDesc": "Controls the maximum number of zombies alive Per Player during a Blood Moon. Nearby players share a group cap of up to 30 zombies. If the cap would be exceeded",
    "goBloodMoonWarningDesc": "Sets when the Blood Moon warning appears on the HUD and the day number changes to red.",
    "goAirDropFrequencyDesc": "How often supply drops occur.",
    "goAirDropRandomTimeDesc": "Allows control over when the air drops appear. Pick a specific time for predictable air drops",
    "goStormFreqDesc": "Adjusts the frequency of storms. None disables storms.",
    "goStormWarningDesc": "Controls whether the player hears the storm siren and sees an on-screen storm warning.",
    "goHeatMapSensitivityDesc": "Controls heat buildup from player activity. Higher heat increases the chance for screamer spawns. Default uses XML config values.",
    "goDayNightLengthDesc": "How many real life minutes it takes for 24 hours to pass in the game.",
    "goDayLightLengthDesc": "Sets the number of in-game daylight hours.",
    "goAirDropMarkerDesc": "Show or hide supply drop markers on the map and compass.",
    "goAllowMapDesc": "Enable in-game map.",
    "goAllowCompassDesc": "Show player compass.",
    "goAllowScreenMarkersDesc": "Show on-screen navigational markers. Map markers remain visible.",
    "goShowLocationInfoDesc": "Show biome and POI name and difficulty.",
    "goShowDayTimeDesc": "Show on-screen day and time information. If set to No",
    "goLootMaxTierDesc": "Sets the highest quality of weapons and items that can appear in loot.",
    "goGlobalLSModifierDesc": "Global multiplier applied to player loot stage. Default uses XML config values.",
    "goBiomeLSModifierDesc": "Loot stage multiplier applied per biome. Default uses XML config values.",
    "goPOITierLSModifierDesc": "Loot stage multiplier based on POI tier. Default uses XML config values.",
    "goLootRespawnDaysDesc": "The number of in-game days before loot containers in unvisited areas reset.",
    "goLootTimerDesc": "Time required to loot containers.",
    "goLootBagChanceDesc": "Multiplier applied to chance for enemies to drop loot bags on death.",
    "goGlobalLootCountDesc": "Global multiplier applied to all loot abundance categories. Default uses individual category settings.",
    "goFoodLootCountDesc": "Amount of food found in containers.",
    "goDrinkLootCountDesc": "Amount of drinks found in containers.",
    "goMedicalLootCountDesc": "Amount of medical supplies found in loot.",
    "goAmmoLootCountDesc": "Amount of ammo found in loot.",
    "goResourceLootCountDesc": "Amount of resource items found in loot.",
    "goArmorLootCountDesc": "Amount of armor and armor parts found in loot.",
    "goMeleeLootCountDesc": "Amount of melee weapons and parts found in loot.",
    "goRangedLootCountDesc": "Amount of ranged weapons and parts found in loot.",
    "goDukesLootCountDesc": "Amount of Duke coins and old cash found in loot.",
    "goCraftingMagazinesLootCountDesc": "Controls the amount of crafting magazines found in loot.",
    "goBookLootCountDesc": "Controls the amount of books and schematics found in loot.",
    "goTreasureMapChanceDesc": "Multiplier applied to chance for treasure maps to spawn in loot containers and enemy loot bags.",
    "goMiningOutputDesc": "Controls the amount of ore gained from mining. Can impact in-game challenges if disabled.",
    "goCropOutputDesc": "Controls the amount of resources harvested from wild and player planted crops. Can impact in-game challenges if disabled.",
    "goSeedDropOutputDesc": "The amount of seeds gained from player planted crop harvest. Does not increase the chance for seeds dropping or seeds from trees.",
    "goHarvestingOutputDesc": "Controls the amount of resources gained from harvesting blocks and items. Does not affect ores",
    "goCropGrowthSpeedDesc": "Adjusts growth speed of player-planted crops and trees. A higher percent results in longer growth time. Note: Existing saves will require replanting crops for changes to take effect.",
    "goCraftingProgressionDesc": "Enable or disable magazine and schematic based crafting progression.",
    "goCraftingMaxTierDesc": "Sets the highest quality of crafted items.",
    "goPointsPerMagazineDesc": "The progression gained from reading skill magazines.",
    "goBackpackCraftingDesc": "Controls what items the player can craft directly from their backpack.",
    "goWorkstationCraftingDesc": "Yes allows crafting in workstations. No allows player backpack crafting only.",
    "goSmeltingTypeDesc": "Controls how forge crafting works. Smelt items into the forge or craft directly using materials from your backpack.",
    "goCraftingTimeDesc": "Time required to craft items.",
    "goCraftingInputDesc": "Amount of materials required for crafting (excludes resource bundles).",
    "goCraftingOutputDesc": "Number of items produced per craft (excludes resource bundles).",
    "goScrappingOutputDesc": "Amount received when scrapping items.",
    "goDewCollectorTimeDesc": "Adjusts the time it takes for the dew collector to produce water.",
    "goDewCollectorOutputDesc": "The amount of water the dew collector generates per cycle.",
    "goDewCollectorInputDesc": "Sets the number of jars required to begin dew collection.",
    "goApiaryTimeDesc": "Adjusts the time it takes for the apiary to produce honey.",
    "goApiaryOutputDesc": "The amount of honey generated per production cycle.",
    "goApiaryInputDesc": "Sets the amount of flowers needed to begin honey production.",
    "goItemDegradationDesc": "How fast weapons and tools lose durability. Default uses XML config values.",
    "goRepairTypesDesc": "Determines how items are repaired: None = No repair Repair Only = Repair Kits Only Combine Only = Repair on Combine Station Both = Repair Kits and Combine Station",
    "goMaxDegradationAmountDesc": "Determines how much an item degrades when repaired.",
    "goTradersEnabledDesc": "Enable trading with NPC traders.",
    "goVendingEnabledDesc": "Enable or disable vending machine functionality.",
    "goTraderHoursDesc": "Controls trader opening and closing hours.",
    "goTraderProtectionDesc": "Sets damage protection for trader compounds",
    "goTraderDialogDesc": "Toggles the trader voice lines and on-screen dialogue.",
    "goGlobalTSModifierDesc": "Global modifier for trader stage progression. Controls the quality and variety of items sold by traders. Default uses XML config values.",
    "goTraderMaxTierDesc": "Sets the highest item quality available for purchase from the trader.",
    "goTraderItemAbundanceDesc": "The quantity of items for sale at the trader. Lower values make supplies more limited and scarce. Default uses XML config values.",
    "goVendingItemAbundanceDesc": "The quantity of items for sale in trader vending machines. Lower values make supplies more limited and scarce. Default uses XML config values.",
    "goTraderResetIntervalDesc": "Sets how often traders reset inventory. Default uses XML config values.",
    "goVendingResetIntervalDesc": "Sets how often trader vending machines reset inventory. Default uses XML config values.",
    "goTraderSellPricesDesc": "Adjusts the price for items players sell to traders.",
    "goTraderBuyPricesDesc": "Adjusts the price for items players purchase from traders.",
    "goTraderBuyLimitDesc": "Maximum number of each item the trader will buy before refusing more. Lower values limit how much you can sell per restock cycle.",
    "goChallengesEnabledDesc": "Enable the in-game challenge system.",
    "goQuestsEnabledDesc": "Enable or disable quests in your game.",
    "goIntroChallengesEnabledDesc": "Enable the step-by-step introductory challenge for new players.",
    "goIntroQuestEnabledDesc": "Bypass the opening buried supply quest to access full quest progression.",
    "goTraderToTraderQuestsEnabledDesc": "Enable the option to receive quests to other traders.",
    "goBuriedQuestsEnabledDesc": "Allow buried quests to appear in the trader quest lists. No = only POI quests.",
    "goPOIQuestsEnabledDesc": "Allow POI quests to appear in the trader quest lists. No = only buried quests.",
    "goQuestsPerTierDesc": "Number of completed quests required to unlock the next tier. Higher values slow progression between tiers. None = no limit and allows access to all quest tiers.",
    "goQuestProgressionDailyLimitDesc": "Number of daily quests that count towards trader progression. Additional quests still grant XP and rewards",
    "goStarterSkillPointsDesc": "Number of skill points awarded after completing intro challenges",
    "goVehicleFuelUsageDesc": "Adjusts the fuel consumption rate for vehicles.",
    "goVehicleEntityDamageDesc": "How much damage vehicles do to entities.",
    "goVehicleBlockDamageDesc": "How much damage vehicles do to blocks.",
    "goVehicleSelfDamageDesc": "How much damage your vehicle receives from collisions.",
    "goElectricalOutputDesc": "Controls how much electrical power is produced.",
    "goSillyCelebrateDesc": "Enable celebratory confetti particles on entity kill. \"Headshots Only\" option triggers confetti for headshot kills. Does not apply to passive animals.",
    "goSillyBigHeadsDesc": "Enable a \"big head mode\" on zombies",
    "goSillyTinyZombiesDesc": "Enable smaller versions of the zombies.",
    "goSillyLowGravityDesc": "Controls the amount of gravity in-game.",
    "goSillySoundsDesc": "Enable humorous sounds for in-game actions.",
    "goSillyBlackandWhiteDesc": "Enable a classic",

    "goDisabled": "Disabled",
    "goVeryLow": "Very Low",
    "goLow": "Low",
    "goDefault": "Default",
    "goHigh": "High",
    "goVeryHigh": "Very High",
    "goAirDropValue": "Every Day",
    "goUnlimited": "Unlimited",
    "goAllDay": "All Day",
    "goAlwaysDay": "Always Day",
    "goAlwaysNight": "Always Night",
    "goAlwaysOpen": "Always Open",
    "goAnyValue": "Any",
    "goBackpack": "Backpack Only",
    "goBarOnly": "Bar Only",
    "goCarriedOnly": "Carried Only",
    "goClaimable": "Claimable",
    "goCombineOnly": "Combine Only",
    "goDeleteAll": "Delete All",
    "goElites": "Elites",
    "goEquipment": "Equipment",
    "goFast": "Fast",
    "goFerals": "Ferals",
    "goHeadshotFinisher": "Headshot Finisher",
    "goHeadshotOnly": "Headshot Only",
    "goInjured": "Injured",
    "goLimited": "Limited",
    "goMedium": "Medium",
    "goMidDayOnly": "Mid Day",
    "goEvening": "Evening",
    "goMorning": "Morning",
    "goNightOnly": "Night",
    "goNormal": "Normal",
    "goNormals": "Normals",
    "goNotClaimable": "Not Claimable",
    "goNotificationsOnly": "Notifications Only",
    "goOnlyClosedOnBM": "BM Closed",
    "goPermaDeath": "Permanent Death",
    "goRadiated": "Radiated",
    "goRepairOnly": "Repair Only",
    "goSlow": "Slow",
    "goSmelter": "Smelter",
    "goSpecials": "Specials",
    "goStrongs": "Strongs",
    "goTech0": "Tech 0",
    "goTech1": "Tech 1",
    "goTech2": "Tech 2",
    "goTech3": "Tech 3",
    "goToolbelt": "Toolbelt Only",
    "goVeryFast": "Very Fast",
    "goVerySlow": "Very Slow",
    "goWorkbenchOnly": "Workbench Only",
    "goXPOnly": "XP Only",
    "goZMAll": "All",
    "goZMDay": "Day",
    "goZMNight": "Night",
    "goZMWalk": "Walk",
    "goZMJog": "Jog",
    "goZMRun": "Run",
    "goZMSprint": "Sprint",
    "goZMNightmare": "Nightmare",
    "goNameOnly": "Name Only",
    "goPercent": "{0}%",
    "goDays": "{0} Days",
    "goDay": "{0} Day",
    "goEnemies": "{0} Enemies",
    "xuiBoth": "Both",
    "xuiDefault": "Default",
    "xuiDurability": "Durability",
    "xuiInstant": "Instant",
    "xuiMaxDurability": "Max Durability",
    "xuiNo": "No",
    "xuiOptionsVideoTexQualityFull": "Full",
    "xuiYes": "Yes",
    "lblAll": "All",
    "lblContextActionRecipes": "Recipes"
};
