export const localizationMap: Record<string, string> = {
    "goRangedDamage": "Ranged Damage",
    "goMeleeDamage": "Melee Damage",
    "goBlockDamage": "Block Damage",
    "goTerrainDamage": "Terrain Damage",
    "goHeadshotMultiplier": "Headshot Multiplier",
    "goIncomingDamage": "Incoming Damage",
    "goWalkSpeed": "Walk Speed",
    "goRunSpeed": "Run Speed",
    "goCrouchSpeed": "Crouch Speed",
    "goCrouchRunSpeed": "Crouch Run Speed",
    "goJumpStrength": "Jump Height",
    "goStaminaRegen": "Stamina Regen",
    "goStaminaUsage": "Stamina Usage",
    "goXPMultiplier": "XP Multiplier",
    "goShowXP": "Show XP",
    "goPlayerLevelBonusApplied": "Level Health/Stam Bonus",
    "goSkillGainRate": "Skill Gain Rate",
    "goSkillPointsPerLevel": "Skill Gain Amount",
    "goDeathPenalty": "Death Penalty",
    "goLoseItemsOnDeathType": "Lose Items Death Type",
    "goLoseItemsOnDeathCount": "Lose Items Death Count",
    "goDegradeItemsOnDeath": "Degrade Items On Death",
    "goDegradeAmountOnDeath": "Degrade Amount On Death",
    "goDropOnDeath": "Drop On Death",
    "goDropOnQuit": "Drop On Quit",
    "goInfectionRate": "Infection Rate",
    "goNewbieCoat": "Allow Newbie Coat",
    "goEncumbranceModifier": "Encumbrance Modifier",
    "goJarRefund": "Jar Refund",
    "goEnemySpawnMode": "Enemy Spawn",
    "goMaxEnemyTier": "Max Enemy Type",
    "goBiomeEnemyDensity": "Biome Enemy Density",
    "goBiomeZombieRespawn": "Biome Enemy Respawn",
    "goBiomeAnimalRespawn": "Biome Animal Respawn",
    "goEntityDamage": "Entity Damage",
    "goEntityIncomingDamage": "Entity Incoming Damage",
    "goBlockDamageAI": "Entity Block Damage",
    "goBlockDamageAIBM": "Blood Moon Block Damage",
    "goHeadshotMode": "Headshot Mode",
    "goShowHealthBars": "Entity Health Bars",
    "goShowEnemyDamage": "Show Entity Damage",
    "goZombieMove": "Zombie Day Speed",
    "goZombieMoveNight": "Zombie Night Speed",
    "goZombieFeralMove": "Zombie Feral Speed",
    "goZombieBMMove": "Zombie Blood Moon Speed",
    "goZombieFeralSense": "Zombie Feral Sense",
    "goAISmellMode": "Zombie AI Smell Mode",
    "goZombieRageChance": "Zombie Rage Chance",
    "goAllowZombieDigging": "Allow Zombie Digging",
    "goZombiesEatAnimals": "Zombies Eat Animals",
    "goGlobalGSModifier": "Global GameStage",
    "goBiomeGSModifier": "Biome GameStage",
    "goBiomeProgression": "Biome Progression",
    "goTemperatureSurvival": "Temperature Survival",
    "goMaxTechType": "Max Tech Type",
    "goWorkstationsInTheWild": "Workstations in the Wild",
    "goBloodMoonFrequency": "Blood Moon Frequency",
    "goBloodMoonRange": "Blood Moon Range",
    "goBloodMoonEnemyCount": "Blood Moon Count",
    "goBloodMoonWarning": "Blood Moon Warning",
    "goAirDropFrequency": "Air Drops",
    "goAirDropRandomTime": "Air Drop Random Time",
    "goStormFreq": "Storm Frequency",
    "goStormWarning": "Storm Warning",
    "goHeatMapSensitivity": "Heatmap Sensitivity",
    "goDayNightLength": "24 Day Cycle",
    "goDayLightLength": "Day Light Length",
    "goAirDropMarker": "Mark Air Drops",
    "goAllowMap": "Allow Map",
    "goAllowCompass": "Allow Compass",
    "goAllowScreenMarkers": "Allow Screen Markers",
    "goShowLocationInfo": "Show Location Info",
    "goShowDayTime": "Show Day/Time",
    "goLootMaxTier": "Loot Max Tier",
    "goGlobalLSModifier": "Global LootStage",
    "goBiomeLSModifier": "Biome LootStage",
    "goPOITierLSModifier": "POI Tier LootStage",
    "goLootRespawnDays": "Loot Respawn Days",
    "goLootTimer": "Loot Time",
    "goLootBagChance": "Loot Bag Chance",
    "goGlobalLootCount": "Global Loot Abundance",
    "goFoodLootCount": "Food Abundance",
    "goDrinkLootCount": "Drink Abundance",
    "goMedicalLootCount": "Medical Abundance",
    "goAmmoLootCount": "Ammo Abundance",
    "goResourceLootCount": "Resource Abundance",
    "goArmorLootCount": "Armor Abundance",
    "goMeleeLootCount": "Melee Abundance",
    "goRangedLootCount": "Ranged Abundance",
    "goDukesLootCount": "Dukes Abundance",
    "goCraftingMagazinesLootCount": "Magazines Abundance",
    "goBookLootCount": "Book Abundance",
    "goTreasureMapChance": "Treasure Map Chance",
    "goMiningOutput": "Mining Output",
    "goCropOutput": "Crop Output",
    "goSeedDropOutput": "Seed Drop Output",
    "goHarvestingOutput": "Harvesting Output",
    "goCropGrowthSpeed": "Crop Growth",
    "goCraftingProgression": "Crafting Progression",
    "goCraftingMaxTier": "Crafting Max Tier",
    "goPointsPerMagazine": "Magazine Points",
    "goBackpackCrafting": "Backpack Crafting",
    "goWorkstationCrafting": "Workstation Crafting",
    "goSmeltingType": "Smelter Type",
    "goCraftingTime": "Crafting Time",
    "goCraftingInput": "Crafting Input",
    "goCraftingOutput": "Crafting Output",
    "goScrappingOutput": "Scrapping Output",
    "goDewCollectorTime": "Dew Collector Time",
    "goDewCollectorOutput": "Dew Collector Output",
    "goDewCollectorInput": "Dew Collector Input",
    "goApiaryTime": "Apiary Time",
    "goApiaryOutput": "Apiary Output",
    "goApiaryInput": "Apiary Input",
    "goItemDegradation": "Item Degradation",
    "goRepairTypes": "Item Repair Types",
    "goMaxDegradationAmount": "Max Degrade Amount",
    "goTradersEnabled": "Trading Enabled",
    "goVendingEnabled": "Vending Machines Enabled",
    "goTraderHours": "Trader Hours",
    "goTraderProtection": "Trader Protection",
    "goTraderDialog": "Trading Dialog",
    "goGlobalTSModifier": "Global TraderStage",
    "goTraderMaxTier": "Trader Max Tier",
    "goTraderItemAbundance": "Trader Item Abundance",
    "goVendingItemAbundance": "Vending Item Abundance",
    "goTraderResetInterval": "Trader Reset Interval",
    "goVendingResetInterval": "Vending Reset Interval",
    "goTraderSellPrices": "Traders Sell Price",
    "goTraderBuyPrices": "Traders Buy Price",
    "goTraderBuyLimit": "Trader Buy Limit",
    "goChallengesEnabled": "Challenges Enabled",
    "goQuestsEnabled": "Quests Enabled",
    "goIntroChallengesEnabled": "Intro Challenges Enabled",
    "goIntroQuestEnabled": "Intro Quest Enabled",
    "goTraderToTraderQuestsEnabled": "Trader to Trader Quests",
    "goBuriedQuestsEnabled": "Buried Quests Enabled",
    "goPOIQuestsEnabled": "POI Quests Enabled",
    "goQuestsPerTier": "Quests per Tier",
    "goQuestProgressionDailyLimit": "Quests per Day",
    "goStarterSkillPoints": "Starter Skill Points",
    "goVehicleFuelUsage": "Vehicle Fuel Usage",
    "goVehicleEntityDamage": "Vehicle Entity Damage",
    "goVehicleBlockDamage": "Vehicle Block Damage",
    "goVehicleSelfDamage": "Vehicle Self Damage",
    "goElectricalOutput": "Electrical Output",
    "goSillyCelebrate": "Celebrate Kills",
    "goSillyBigHeads": "Big Heads",
    "goSillyTinyZombies": "Tiny Zombies",
    "goSillyLowGravity": "Gravity",
    "goSillySounds": "Silly Sounds",
    "goSillyBlackandWhite": "Black and White",
    "goDisabled": "Disabled",
    "goVeryLow": "Very Low",
    "goLow": "Low",
    "goDefault": "Default",
    "goHigh": "High",
    "goVeryHigh": "Very High",
    "goAirDropValue": "Every Day",
    "goUnlimited": "Unlimited",
    "goAllDay": "All Day",
    "goAlwaysDay": "Always Day",
    "goAlwaysNight": "Always Night",
    "goAlwaysOpen": "Always Open",
    "goAnyValue": "Any",
    "goBackpack": "Backpack Only",
    "goBarOnly": "Bar Only",
    "goCarriedOnly": "Carried Only",
    "goClaimable": "Claimable",
    "goCombineOnly": "Combine Only",
    "goDeleteAll": "Delete All",
    "goElites": "Elites",
    "goEquipment": "Equipment",
    "goFast": "Fast",
    "goFerals": "Ferals",
    "goHeadshotFinisher": "Headshot Finisher",
    "goHeadshotOnly": "Headshot Only",
    "goInjured": "Injured",
    "goLimited": "Limited",
    "goMedium": "Medium",
    "goMidDayOnly": "Mid Day",
    "goEvening": "Evening",
    "goMorning": "Morning",
    "goNightOnly": "Night",
    "goNormal": "Normal",
    "goNormals": "Normals",
    "goNotClaimable": "Not Claimable",
    "goNotificationsOnly": "Notifications Only",
    "goOnlyClosedOnBM": "BM Closed",
    "goPermaDeath": "Permanent Death",
    "goRadiated": "Radiated",
    "goRepairOnly": "Repair Only",
    "goSlow": "Slow",
    "goSmelter": "Smelter",
    "goSpecials": "Specials",
    "goStrongs": "Strongs",
    "goTech0": "Tech 0",
    "goTech1": "Tech 1",
    "goTech2": "Tech 2",
    "goTech3": "Tech 3",
    "goToolbelt": "Toolbelt Only",
    "goVeryFast": "Very Fast",
    "goVerySlow": "Very Slow",
    "goWorkbenchOnly": "Workbench Only",
    "goXPOnly": "XP Only",
    "goZMAll": "All",
    "goZMDay": "Day",
    "goZMNight": "Night",
    "goZMWalk": "Walk",
    "goZMJog": "Jog",
    "goZMRun": "Run",
    "goZMSprint": "Sprint",
    "goZMNightmare": "Nightmare",
    "goNameOnly": "Name Only",
    "goPercent": "{0}%",
    "goDays": "{0} Days",
    "goDay": "{0} Day",
    "goEnemies": "{0} Enemies",
    "xuiBoth": "Both",
    "xuiDefault": "Default",
    "xuiDurability": "Durability",
    "xuiInstant": "Instant",
    "xuiMaxDurability": "Max Durability",
    "xuiNo": "No",
    "xuiOptionsVideoTexQualityFull": "Full",
    "xuiYes": "Yes",
    "lblAll": "All",
    "lblContextActionRecipes": "Recipes"
};
